### ISSUE TITLE
Dapper

### ISSUE THREAD

**Issue by ghost** [stoveproject/Stove#151]
Hi,

thanks for your project,  i have a question about dapper. 
how to use the dapper in your framework.

thanks!

**Comment by osoykan** [comment]
Hi,

Sorry for late response. 

Dapper actually is a secondary orm choice can not be used alone. That's why you need to compose your application firstly with EF or NH and after that setup Dapper with `UseStoveDapper()`.

It connects with same Uow structure and gets the database connection from primary orm choice which means that EF or NH. 

It has repository structure like `IDapperRepository<T>` you can easily inject it and use it. Of course you can write the one of your custom repo too.

I hope this will answer your question.

**Comment by ghost** [comment]
Hi,
Really thanks for your reply.
the information is very useful for me. i prefer to use dapper in the framework, its more efficient for me.

thanks!
